<?php 

$bible= array(
/*
    array("http://www.magnificat.ca/textes/bible/genese.htm","Gn","Gn"),
    array("http://www.magnificat.ca/textes/bible/exode.htm","Ex","Ex"),
   array("http://www.magnificat.ca/textes/bible/levitique.htm","Lv","Lv"),
    array("http://www.magnificat.ca/textes/bible/nombres.htm","Nb","Nm"),
    array("http://www.magnificat.ca/textes/bible/deuteronome.htm","Dt","Dt"),
    array("http://www.magnificat.ca/textes/bible/josue.htm","Jos","Jos"),
    array("http://www.magnificat.ca/textes/bible/juges.htm","Jg","Jdc"),
    array("http://www.magnificat.ca/textes/bible/ruth.htm","Rt","Rt"),
    array("http://www.magnificat.ca/textes/bible/1samuel.htm","I S","1Rg"),
    array("http://www.magnificat.ca/textes/bible/2samuel.htm","II S","2Rg"),
    array("http://www.magnificat.ca/textes/bible/1rois.htm","I R","3Rg"),
    array("http://www.magnificat.ca/textes/bible/2rois.htm","II R","4Rg"),
	array("http://www.magnificat.ca/textes/bible/1chroniques.htm","I Ch","1Par"),
	array("http://www.magnificat.ca/textes/bible/2chroniques.htm","II Ch","2Par"),
	array("http://www.magnificat.ca/textes/bible/esdras.htm","Esd","Esr"),
	array("http://www.magnificat.ca/textes/bible/nehemie.htm","Ne","Neh"),
	array("http://www.magnificat.ca/textes/bible/tobie.htm","Tb","Tob"),
	array("http://www.magnificat.ca/textes/bible/judith.htm","Jdt","Jdt"),
	array("http://www.magnificat.ca/textes/bible/esther.htm","Est","Est"),
	array("http://www.magnificat.ca/textes/bible/1maccabees.htm","I M","1Mcc"),
	array("http://www.magnificat.ca/textes/bible/2maccabees.htm","II M","2Mcc"),
	array("http://www.magnificat.ca/textes/bible/job.htm","Jb","Job"),
	array("http://www.magnificat.ca/textes/bible/psaumes.htm","Ps","Ps"),
	array("http://www.magnificat.ca/textes/bible/proverbes.htm","Pr","Pr"),
	array("http://www.magnificat.ca/textes/bible/ecclesiaste.htm","Qo","Ecl"),
	array("http://www.magnificat.ca/textes/bible/cantiques.htm","Ct","Ct"),
	array("http://www.magnificat.ca/textes/bible/sagesse.htm","Sg","Sap"),
	array("http://www.magnificat.ca/textes/bible/ecclesiastique.htm","Si","Sir"),
	array("http://www.magnificat.ca/textes/bible/isaie.htm","Is","Is"),
	array("http://www.magnificat.ca/textes/bible/jeremie.htm","Jr","Jr"),
	array("http://www.magnificat.ca/textes/bible/lamentations.htm","Lm","Lam"),
	array("http://www.magnificat.ca/textes/bible/baruch.htm","Ba","Bar"),
	array("http://www.magnificat.ca/textes/bible/ezechiel.htm","Ez","Ez"),
	array("http://www.magnificat.ca/textes/bible/daniel.htm","Dn","Dn"),
	array("http://www.magnificat.ca/textes/bible/osee.htm","Os","Os"),
	array("http://www.magnificat.ca/textes/bible/joel.htm","Jl","Joel"),
	array("http://www.magnificat.ca/textes/bible/amos.htm","Am","Am"),
	array("http://www.magnificat.ca/textes/bible/abdias.htm","Ab","Abd"),
	array("http://www.magnificat.ca/textes/bible/jonas.htm","Jon","Jon"),
	array("http://www.magnificat.ca/textes/bible/michee.htm","Mi","Mch"),
	array("http://www.magnificat.ca/textes/bible/nahum.htm","Na","Nah"),
	array("http://www.magnificat.ca/textes/bible/habaquq.htm","Ha","Hab"),
	array("http://www.magnificat.ca/textes/bible/sophonie.htm","So","Soph"),
	array("http://www.magnificat.ca/textes/bible/aggee.htm","Ag","Agg"),
	array("http://www.magnificat.ca/textes/bible/zacharie.htm","Za","Zach"),
	array("http://www.magnificat.ca/textes/bible/malachie.htm","Ml","Mal"),
	*/
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-01.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-02.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-03.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-04.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-05.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-06.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-07.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-08.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-09.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-10.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-11.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-12.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-13.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-14.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-15.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-16.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-17.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-18.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-19.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-20.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-21.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-22.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-23.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-24.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-25.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-26.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-27.htm","Mt","Mt"),
	array("http://www.magnificat.ca/textes/bible/evangiles/matthieu-28.htm","Mt","Mt"),
	/*
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-01.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-02.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-03.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-04.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-05.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-06.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-07.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-08.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-09.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-10.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-11.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-12.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-13.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-14.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-15.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/marc-16.htm","Mc","Mc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-01.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-02.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-03.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-04.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-05.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-06.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-07.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-08.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-09.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-10.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-11.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-12.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-13.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-14.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-15.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-16.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-17.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-18.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-19.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-20.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-21.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-22.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-23.htm","Lc","Lc"),
	array("http://www.magnificat.ca/textes/bible/evangiles/luc-24.htm","Lc","Lc"),
	
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-01.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-02.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-03.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-04.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-05.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-06.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-07.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-08.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-09.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-10.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-11.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-12.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-13.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-14.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-15.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-16.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-17.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-18.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-19.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-20.htm","Jn","Jo"),
	array("http://www.magnificat.ca/textes/bible/evangiles/jean-21.htm","Jn","Jo"),
	
	array("http://www.magnificat.ca/textes/bible/actes/actes-01.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-02.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-03.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-04.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-05.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-06.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-07.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-08.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-09.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-10.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-11.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-12.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-13.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-14.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-15.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-16.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-17.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-18.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-19.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-20.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-21.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-22.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-23.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-24.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-25.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-26.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-27.htm","Act","Act"),
	array("http://www.magnificat.ca/textes/bible/actes/actes-28.htm","Act","Act"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/romains-01.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-02.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-03.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-04.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-05.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-06.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-07.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-08.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-09.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-10.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-11.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-12.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-13.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-14.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-15.htm","Rom","Rom"),
	array("http://www.magnificat.ca/textes/bible/epitres/romains-16.htm","Rom","Rom"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-01.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-02.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-03.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-04.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-05.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-06.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-07.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-08.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-09.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-10.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-11.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-12.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-13.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-14.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-15.htm","I Cor","1Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/1corinthiens-16.htm","I Cor","1Cor"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-01.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-02.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-03.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-04.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-05.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-06.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-07.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-08.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-09.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-10.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-11.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-12.htm","II Cor","2Cor"),
	array("http://www.magnificat.ca/textes/bible/epitres/2corinthiens-13.htm","II Cor","2Cor"),
	/*
	array("http://www.magnificat.ca/textes/bible/epitres/galates.htm","Gal","Gal"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/ephesiens.htm","Eph","Eph"),
	array("http://www.magnificat.ca/textes/bible/epitres/philippiens.htm","Phil","Phlp"),
	array("http://www.magnificat.ca/textes/bible/epitres/colossiens.htm","Col","Col"),
	array("http://www.magnificat.ca/textes/bible/epitres/1thessaloniciens.htm","I Thes","1Thes"),
	array("http://www.magnificat.ca/textes/bible/epitres/2thessaloniciens.htm","II Thes","2Thes"),
	array("http://www.magnificat.ca/textes/bible/epitres/2thessaloniciens.htm","II Thes","2Thes"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/1timothee.htm","I Tim","1Tim"),
	array("http://www.magnificat.ca/textes/bible/epitres/2timothee.htm","II Tim","2Tim"),
	array("http://www.magnificat.ca/textes/bible/epitres/tite.htm","Tite","Tit"),
	
	array("http://www.magnificat.ca/textes/bible/epitres/philemon.htm","Philem","Phlm"),

	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-01.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-02.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-03.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-04.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-05.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-06.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-07.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-08.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-09.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-10.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-11.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-12.htm","H&eacute;br","Hbr"),
	array("http://www.magnificat.ca/textes/bible/epitres/hebreux-13.htm","H&eacute;br","Hbr"),

	array("http://www.magnificat.ca/textes/bible/epitres/jacques.htm","Jac","Jac"),
	array("http://www.magnificat.ca/textes/bible/epitres/1pierre.htm","I Pier","1Ptr"),
	array("http://www.magnificat.ca/textes/bible/epitres/2pierre.htm","II Pierre","2Ptr"),
	array("http://www.magnificat.ca/textes/bible/epitres/1jean.htm","I Jn","1Jo"),
	array("http://www.magnificat.ca/textes/bible/epitres/2jean.htm","II Jn","2Jo"),
	array("http://www.magnificat.ca/textes/bible/epitres/3jean.htm","III Jn","3Jo"),
	array("http://www.magnificat.ca/textes/bible/epitres/jude.htm","Jud","Jud"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-01.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-02.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-03.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-04.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-05.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-06.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-07.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-08.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-09.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-10.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-11.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-12.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-13.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-14.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-15.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-16.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-17.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-18.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-19.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-20.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-21.htm","Apoc","Apc"),
	array("http://www.magnificat.ca/textes/bible/apocalypse/apocalypse-22.htm","Apoc","Apc"),
	*/
);
//print_r($bible);
foreach($bible as $livre) {
	print "\r\n".$livre[0]." ".$livre[1]." ".$livre[2];

$page=file_get_contents($livre[0]);
$content= strip_tags($page);
$lignes=explode("<br />",nl2br($content));
//print_r($lignes);
foreach ($lignes as $ligne) {
	//print"\r\n".$ligne;
	if(strpos ($ligne, "Chapitre")) $ligne=null;
	//print"\r\n".strlen($ligne);
	if(strlen ( $ligne)<5) $ligne=null;
	if(strstr($ligne,$livre[1]." ") == false) $ligne=null;
	$chose = strstr ( $ligne , ". " , true );
	$chose=str_replace($livre[1]." ","",$chose);
	$chose=str_replace(",",":",$chose);
	if(strlen($ligne) > 3) $output.= "".$chose." ".str_replace(strstr ( $ligne , ". " , true ),"",$ligne);
}
$output=str_replace(" . "," ",$output);
$output=html_entity_decode($output);
$output=trim($output);

if(strstr($livre[0],"-")) {
	//if(strstr($livre[0],"-01")) $output="";
}
else $output="";

}

print $output;
//print "\r\n".$livre[0]." ".$livre[1]." ".$livre[2];
print"\r\n C:/Program Files/VulSearch/Text/".$livre[2].".fn";
file_put_contents("C:/Program Files/VulSearch/Text/".$livre[2].".fn", $output);


?>